# Jupyter Book configuration
# https://jupyterbook.org/en/stable/customize/config.html

title: Introduction to Planetary Science
author: Tim Lichtenberg
copyright: "2026"

execute:
  execute_notebooks: "off"

# LaTeX / PDF settings
latex:
  latex_engine: xelatex
  latex_documents:
    targetname: IntroductionToPlanetaryScience.tex

bibtex_bibfiles:
  - references.bib

sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    bibtex_reference_style: author_year
    bibtex_default_style: chicago
    suppress_warnings:
      - bibtex.duplicate_citation
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mathjax3_config:
      tex:
        packages:
          "[+]":
            - ams
            - physics
        macros:
          dv: ["\\frac{\\mathrm{d} #1}{\\mathrm{d} #2}", 2]
          dd: ["\\mathrm{d}"]
          pdv: ["\\frac{\\partial #1}{\\partial #2}", 2]
          Msun: ["M_{\\odot}"]
          Rsun: ["R_{\\odot}"]
          Lsun: ["L_{\\odot}"]
          Mearth: ["M_{\\oplus}"]
          Rearth: ["R_{\\oplus}"]
          Mjup: ["M_{\\mathrm{J}}"]
          Rjup: ["R_{\\mathrm{J}}"]
          kB: ["k_{\\mathrm{B}}"]
    latex_elements:
      preamble: |
        \usepackage{unicode-math}
        \setmainfont{Inter}[
          UprightFont    = *-Regular,
          BoldFont       = *-Bold,
          ItalicFont     = *-Italic,
          BoldItalicFont = *-BoldItalic,
        ]
        \setsansfont{Inter}[
          UprightFont    = *-Regular,
          BoldFont       = *-Bold,
          ItalicFont     = *-Italic,
          BoldItalicFont = *-BoldItalic,
        ]
        \setmathfont{FiraMath-Regular.otf}

        \newcommand{\dv}[2]{\frac{\mathrm{d} #1}{\mathrm{d} #2}}
        \renewcommand{\dd}{\mathrm{d}}
        \newcommand{\pdv}[2]{\frac{\partial #1}{\partial #2}}
      papersize: a4paper
      pointsize: 11pt

html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false

repository:
  url: https://github.com/FormingWorlds/IntroductionToPlanetaryScience
  branch: main
  path_to_book: book
